# Generated by Django 5.0 on 2024-01-17 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsmaincategory', '0005_category_alter_cars_year_cars_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carsmaincategory.category'),
        ),
    ]
