# Generated by Django 5.0 on 2024-01-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsmaincategory', '0006_alter_cars_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='carsmaincategory.tagpost'),
        ),
    ]
